export const itemIcons: Map<string, Map<string, string>> = new Map([
  [
    "amenity",
    new Map([
      ["hospital", "\uD83C\uDFE5"],
      ["clinic", "\uD83C\uDFE5"],
      ["pharmacy", "\uD83D\uDC8A"],
      ["veterinary", "\uD83D\uDC3E"],
      ["school", "\uD83C\uDF93"],
      ["restaurant", "\uD83C\uDF74"],
      ["post_office", "\uD83D\uDCEE"],
      ["government", "\uD83C\uDFDB\uFE0F"],
      ["bank", "\uD83C\uDFE6"],
      ["fuel", "\u26FD"],
      ["bus_stop", "\uD83D\uDE8C"],
      ["community_centre", "\uD83C\uDFE0"],
      ["arts_centre", "\uD83C\uDFA8"],
      ["social_facility", "\uD83E\uDE86"],
      ["embassy", "\uD83C\uDFE2"],
      ["police", "\uD83D\uDEA8"],
      ["fire_station", "\uD83D\uDE92"],
      ["library", "\uD83D\uDCDA"],
      ["place_of_worship", "\u26EA"],
      ["bar", "\uD83C\uDF7A"],
      ["cafe", "\u2615"],
      ["college", "\uD83C\uDFEB"],
      ["university", "\uD83C\uDFEB"],
      ["theatre", "\uD83C\uDFAD"],
      ["driving_school", "🚗"],
    ]),
  ],
  [
    "shop",
    new Map([
      ["supermarket", "\uD83D\uDECD\uFE0F"],
      ["convenience", "🛒"],
      ["mall", "\uD83C\uDFEC"],
      ["marketplace", "\uD83D\uDED2"],
      ["bakery", "\uD83C\uDF5E"],
      ["butcher", "\uD83D\uDC37"],
      ["greengrocer", "\uD83C\uDF53"],
      ["clothes", "\uD83D\uDC55"],
      ["electronics", "\uD83D\uDCF1"],
      ["furniture", "\uD83C\uDFE1"],
      ["jewelry", "\uD83D\uDC8D"],
      ["hardware", "\uD83D\uDEE0"],
      ["sports", "\uD83C\uDFCB"],
    ]),
  ],
  [
    "tourism",
    new Map([
      ["attraction", "\uD83C\uDFE1"],
      ["hostel", "\uD83C\uDFE8"],
      ["museum", "\uD83C\uDFF0"],
      ["information", "ℹ️"],
      ["hotel", "\uD83C\uDFE8"],
      ["camp_site", "\uD83C\uDFD5"],
      ["viewpoint", "\uD83C\uDFDE"],
    ]),
  ],
  [
    "natural",
    new Map([
      ["wood", "\uD83C\uDF32"],
      ["reserve", "\uD83C\uDF33"],
      ["water", "\uD83D\uDCA7"],
      ["peak", "\u26F0"],
      ["beach", "\uD83C\uDFD6"],
      ["wetland", "\uD83C\uDF3F"],
    ]),
  ],
  [
    "leisure",
    new Map([
      ["park", "\uD83C\uDF33"],
      ["sports_centre", "\uD83C\uDFCB\uFE0F"],
      ["stadium", "\uD83C\uDFDF"],
      ["pitch", "\u26BD"],
      ["track", "\uD83C\uDFC3"],
      ["playground", "\uD83C\uDFAE"],
      ["garden", "\uD83C\uDF3F"],
    ]),
  ],
  [
    "sport",
    new Map([
      ["soccer", "\u26BD"],
      ["tennis", "\uD83C\uDFBE"],
      ["basketball", "\uD83C\uDFC0"],
      ["swimming", "\uD83C\uDFCA"],
      ["running", "\uD83C\uDFC3"],
      ["cycling", "\uD83D\uDEB4"],
      ["golf", "\u26F3"],
    ]),
  ],
  [
    "office",
    new Map([
      ["government", "\uD83C\uDFDB\uFE0F"],
      ["company", "\uD83D\uDCBC"],
      ["ngo", "\uD83D\uDCDA"],
      ["administrative", "\uD83D\uDCC1"],
      ["consulting", "\uD83D\uDCC8"],
      ["it", "\uD83D\uDCBB"],
      ["law", "⚖️"],
      ["real_estate", "\uD83C\uDFE2"],
      ["media", "\uD83C\uDF10"],
      ["architecture", "\uD83C\uDFD7"],
      ["insurance", "\uD83D\uDCB8"],
      ["finance", "\uD83D\uDCB5"],
      ["financial", "\uD83D\uDCB5"],
      ["education", "\uD83C\uDFEB"],
      ["telecommunication", "\uD83D\uDCDE"],
      ["research", "\uD83C\uDF0D"],
      ["diplomatic", "\uD83D\uDDFA"],
      ["newspaper", "\uD83D\uDCF0"],
      ["estate_agent", "🏘️"],
      ["association", "🤝"],
    ]),
  ],
]);
